dist: bionic
language: python
python: 3.8.2
install:
  - pip install -r requirements.txt
  - pip install codecov


script:
  - coverage erase
  - coverage run test_app.py && coverage html
  - pylint --output-format=text test_app.py
  - pytest


after_success:
  - codecov
