dist: bionic
language: python
python: 3.8.2
install:
  - pip install -r requirements.txt
  - pip install codecov


script:
  - pylint --output-format=text test_app.py
  - pytest -v


after_success:
  - codecov
