version: 2
jobs:
    build:
        docker:
        - image: circleci/node:8.11
        environment:
            - NODE_ENV: "production"
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: install dependencies
                command: npm install
            - run:
                name: make builds
                command: npm run build
            - store_artifacts:
                path: static/js
                destination: bundles